import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// import { Great_Vibes } from 'next/font/google'
import { Inika } from 'next/font/google'


// const greatVibes = Great_Vibes({
//   subsets: ['latin'],
//   weight: '400',
//   variable: '--font-script',
// })


const inika = Inika({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: '--font-inika',
  display: "swap",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inika.className}>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} ${greatVibes.variable} ${inika.variable} antialiased`}
        className={`${inika.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
