services:
  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: azec
      POSTGRES_DB: recipes
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - '5432:5432'


  backend:
    container_name: backend
    build: ./backend
    ports:
      - '3000:3000'
    depends_on: 
      database:
        condition: service_started
    volumes:
      - ./backend:/app
    environment:
      - WATCHPACK_POLLING=true

  frontend:
    container_name: frontend
    build:
      context: ./frontend/recipes
      args:
        BACKEND_URL: ${BACKEND_URL}
    ports:
      - '3005:3000'
    depends_on: 
      - backend
    env_file:
      - ./frontend/recipes/.env

volumes:
  postgres-data:

