# Use official Node.js image
FROM node:alpine3.23

# Set working directory
WORKDIR /app
# Copy package files first (for caching)
COPY package*.json ./
# Install dependencies
RUN npm install

COPY prisma ./prisma/
RUN npx prisma generate


COPY . .

#EXPOSE 3000
#- check .env files with database url 

# Copy application code
# Expose the app port
# Start the app
CMD ["npm", "start", "server.js" ]
